# Generated by Django 3.0.6 on 2020-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자')], max_length=10, null=True),
        ),
    ]
