# Generated by Django 3.0.5 on 2020-04-28 14:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0002_auto_20200428_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
