# Generated by Django 3.0.6 on 2020-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0003_auto_20200428_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
