# Generated by Django 3.0.6 on 2020-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0004_curriculum_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='today',
            field=models.BooleanField(default=True),
        ),
    ]
