# Generated by Django 3.0.6 on 2020-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_bookreview',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories_BookReview'},
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=models.TextField(),
        ),
    ]
