# Generated by Django 3.0.6 on 2020-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0004_auto_20200801_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=models.TextField(),
        ),
    ]
