# Generated by Django 3.0.6 on 2020-08-02 06:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0005_auto_20200801_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
    ]
