# Generated by Django 3.0.6 on 2020-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0006_auto_20200802_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=models.TextField(),
        ),
    ]
